### ISSUE TITLE
Scanning multiple s3 buckets?

### ISSUE THREAD

**Issue by poVoq** [db0/fedi-safety#13]
I am thinking about setting up a shared object storage for Lemmy instances to collaborate with https://garagehq.deuxfleurs.fr/ and it would be interesting to also share resources for ML image scanning.

However it seems like every Pict-rs uses it's own bucket and thus you can only scan one instance, or am I misunderstanding how it works?

I assume sharing an fedi-safty instance like that would make it a bit slower, but keep the RAM etc requirements manageable.

**Comment by db0** [comment]
You can run two instances of fedi-safety if you have enough VRAM, or you can modify the code to rount-robin check the buckets

**Comment by poVoq** [comment]
Vram is the main issue indeed.

**Comment by db0** [comment]
Then round-robin in your best option
