### ISSUE TITLE
Multiple local file locations?

### ISSUE THREAD

**Issue by poVoq** [db0/fedi-safety#8]
I was thinking of using this to also scan other public user uploads on the same server (XMPP, Wiki etc.), but it seems this only supports a single location?

Would it be hard to add this?

**Comment by db0** [comment]
It wouldn't be particularly hard to scan more than one location. Are you running it in the same server, or via ssh?

**Comment by poVoq** [comment]
All local, same server.

**Comment by poVoq** [comment]
Thinking about this a bit more? What would be the overhead of simply starting the process multiple times pointing to different config files for different storage locations?

I am mostly concerned about limited VRAM.

**Comment by db0** [comment]
to run the script twice? If you do it parallel, it would double the VRAM used

**Comment by poVoq** [comment]
Sure, but how much of that is duplicated overhead and how much is simply a result of scanning other images?

I guess keeping the AI model in vram is what takes most and thus that part would be pure duplicated overhead?

**Comment by db0** [comment]
> And what would be the difference between running the script once with 10 threads, vs. running it twice with 5 threads each?

double the VRAM without any benefit in speed

**Comment by poVoq** [comment]
I see. Well in that case my original feature request is still valid 😊
